#!/usr/bin/env python3
"""
gen_antenna_data.py  --  Read antenna CSV and generate antenna_data.py
Usage: python gen_antenna_data.py <input.csv> [output.py]
       output defaults to antenna_data.py
"""
import csv
import sys
from pathlib import Path


def generate(csv_path: Path, out_path: Path) -> None:
    rows = []
    with csv_path.open(newline='') as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append((
                int(row['msb']),
                int(row['lsb']),
                row['path'],
                row['description'],
            ))

    lines = [
        '# Auto-generated by gen_antenna_data.py -- do not edit by hand',
        f'# Source: {csv_path.name}',
        '',
        'ANTENNA_DATA: list[tuple[int, int, str, str]] = [',
        '    # (msb, lsb, path, description)',
    ]

    for msb, lsb, path, desc in rows:
        # escape any single quotes in path or description
        path_s = path.replace("'", "\\'")
        desc_s = desc.replace("'", "\\'")
        lines.append(f"    ({msb:3d}, {lsb:3d},  '{path_s}',  '{desc_s}'),")

    lines += [']', '']

    out_path.write_text('\n'.join(lines))
    print(f"Wrote {len(rows)} entries to {out_path}")


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    csv_file = Path(sys.argv[1])
    out_file = Path(sys.argv[2]) if len(sys.argv) > 2 else Path('antenna_data.py')
    generate(csv_file, out_file)