#!/usr/bin/env bash
# =============================================================================
# gen_antenna_data.sh -- Generate antenna_data.h from a CSV file
# Usage: gen_antenna_data.sh <input.csv> [output.h]
#        output defaults to antenna_data.h
# =============================================================================
set -euo pipefail

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <input.csv> [output.h]" >&2
    exit 1
fi

CSV_FILE="$1"
OUT_FILE="${2:-antenna_data.h}"
GUARD="ANTENNA_DATA_H"
TIMESTAMP=$(date -u '+%Y-%m-%d %H:%M:%S UTC')

if [[ ! -f "$CSV_FILE" ]]; then
    echo "Error: CSV file '$CSV_FILE' not found." >&2
    exit 1
fi

# -----------------------------------------------------------------------
# Write the header
# -----------------------------------------------------------------------
cat > "$OUT_FILE" <<HEADER
// Auto-generated by gen_antenna_data.sh -- do not edit by hand
// Source:    ${CSV_FILE}
// Generated: ${TIMESTAMP}

#ifndef ${GUARD}
#define ${GUARD}

#include <cstdint>

struct AntennaEntry {
    uint16_t    index;          // msb*256 + lsb
    const char *path;
    const char *description;
};

// clang-format off
static const AntennaEntry ANTENNA_DATA[] = {
    //  index    path                                    description
HEADER

# -----------------------------------------------------------------------
# Parse CSV rows (skip header line), emit one initializer per row
# -----------------------------------------------------------------------
tail -n +2 "$CSV_FILE" | while IFS=',' read -r msb lsb path description; do
    # strip surrounding whitespace
    msb="${msb// /}"
    lsb="${lsb// /}"
    path="${path// /}"
    # skip blank or non-numeric lines
    [[ "$msb" =~ ^[0-9]+$ ]] || continue
    # description may contain commas that were re-joined -- handle quoted fields
    # strip leading/trailing whitespace and surrounding double-quotes if present
    description="${description#"${description%%[![:space:]]*}"}"
    description="${description%"${description##*[![:space:]]}"}"
    description="${description#\"}"
    description="${description%\"}"

    # escape backslashes then double-quotes for C string literals
    path="${path//\\/\\\\}"
    path="${path//\"/\\\"}"
    description="${description//\\/\\\\}"
    description="${description//\"/\\\"}"

    index=$(( msb * 256 + lsb ))

    printf '    { %5d,  %-35s  "%s" },\n' \
        "$index" "\"${path}\"," "${description}"

done >> "$OUT_FILE"

# -----------------------------------------------------------------------
# Write the footer
# -----------------------------------------------------------------------
cat >> "$OUT_FILE" <<FOOTER
};
// clang-format on

static const std::size_t ANTENNA_DATA_COUNT =
    sizeof(ANTENNA_DATA) / sizeof(ANTENNA_DATA[0]);

#endif // ${GUARD}
FOOTER

echo "Wrote $(tail -n +2 "$CSV_FILE" | wc -l | tr -d ' ') entries to ${OUT_FILE}"